[package]
name = "font-pixelator"
version = "0.1.0"
edition = "2018"


[dependencies]
usvg = "0.14.1"
ttf-parser = "0.11.0"
ttf-utils = "0.1.3"
tiny-skia = "0.5.1"
clap = "2.33.3"
quick_from = "0.1.0"
png = "0.16.8"
geo-booleanop = "0.3.2"
geo = "0.16.0"

